atom/spell-check

lib/main.coffee
Please, consider adding asciidoc grammar to defaults. As well as with Markdown, vast majority of AsciiDoc users expect spell-checking to be enabled by default. Here is a related issue for `language-asciidoc` package asciidoctor/atom-language-asciidoc#5.
=> Add asciidoc grammar to defaults

menus/spell-check.cson
Part of atom/settings-view#354
This removes Correct Spelling from mini editors' context menus - if this is a bit too far-reaching I can limit it to mini editors in panes without file paths, but the current behavior is confusing since it looks for a language grammar.
=> Remove Correct Spelling from mini editor context menu

README.md
Closes https://github.com/atom/spell-check/issues/68, and hopefully prevents further confusion about this (I remember a few similar issues opened in the past several weeks). As far as remember (I glanced the history a few weeks back) -- other dictionaries were supported at some point on some OSes, but that was removed later on.
cc @kevinsawicki
=> Clarify that EN_US is the only supported dictionary currently

styles/spell-check.atom-text-editor.less
This PR makes the border stronger and easier to spot.
Before:
After:
- 2px width
- `dotted` instead of dashed, so that it doesn't look strange when narrow.
- less transparent red
Fixes #86
=> Stronger underline

lib/misspelling-view.coffee
Previously I made some attempts to migrate our legacy jQuery code to vanilla HTML. Although honorable, that requires a bit of time and has the risk of introducing regressions.
This, on the other hand, is a quick win that, in conjunction with https://github.com/atom/image-view/pull/47, allows us to make startup `50ms` faster by deferring jQuery initialization until the last possible moment (i.e. not during startup).
=> Defer jQuery initialization

package.json
As of atom/node-spellchecker#33 (v3.2.3), the default language used is that of the `LANG` environment variable. This is an (non-closing) improvement for those subscribed to #21.
=> updates spellchecker to use system language

lib/corrections-view.coffee, lib/spell-check-view.coffee, spec/spell-check-spec.coffee
We were using a deprecated `replicate` custom property. Moreover, this marks the entire layer as `{maintainHistory: false}`, rather than specifying the same option on every single marker.
/cc: @nathansobo
=> Add marker layers on TextEditor and stop using marker custom properties

lib/main.coffee
Previously, upon package deactivation, we were destroying all the editors where spell-check was enabled. This pull-request changes it so that we destroy only the view which, in turn, will clear all the created markers and decorations.
@dmoonfire: can you confirm this was the intended behavior?
=> Don't destroy editors when deactivating package

lib/main.coffee
=> Prevent toggling spell-check when there is no active text editor

lib/main.coffee, lib/spell-check-view.coffee, spec/spell-check-spec.coffee
Displaying the corrections for a misspelled word as context menu options as described in #54. This is my first OSS contribution so any feedback on the design or workflow would be great.
=> Display corrections in context menu for #54

lib/main.coffee
Soon we're going to rewrite this package to only check the spelling of the content on screen. Until then, we're just going to avoid spell-checking large files.
/cc @ungb @lee-dohm 
Closes https://github.com/atom/spell-check/pull/170
@steelbrain - I'd prefer to perform the check for `largeFileMode` even earlier. There's no need to even create a `SpellCheckView` for large files.
=> Don't spell check large files (for now)

lib/system-checker.coffee
For Fedora-based distributions, the path for dictionaries is `/usr/share/myspell`. (Closes #164)
=> Added `/usr/share/myspell` as a search path

package.json
None
Fix the github README link:
Fix the wrong anchor (just removed the trailing `-`).
N.A.
Better user experience
none
none
=> fix the github README link

lib/system-checker.coffee
Windows 7 doesn't correct use the packaged `en-US` dictionary when no settings are included in the dictionary.
On Windows 7 (#162), `spell-check` does not correctly fall back to `en-US` dictionary inside the `node-spellcheck` because we ship a ASAR-packed archive. The fallback directory search was based on the original version of `node-spellcheck`'s check for local director but did not include the "unpacked" logic that is there today. In version 3.4.4 of `node-spellcheck`, a method was provided to get the library's search path which we are now using instead of duplicating the (incorrect) logic that doesn't handle ASAR packing.
Originally, we copied the search path from `node-spellcheck`. An alternative is to update our search path logic to use the same `try`/`catch` logic to handle …
=> Fallback to the dictionary path provided by node-spellchecker.

lib/main.coffee, spec/spell-check-spec.coffee
Fixes #201. (Includes a spec to guard against this)
See issue #201 - `spell-check` retains a global map of all opened editors, and does not release them upon editor destruction.
Fewer memory leaks (this leaks entire editor objects, although thankfully the impact is generally limited because `TextEditor` nulls out various references during its destruction).
=> Remove editors from `spellCheckViews` after destruction

lib/main.coffee, lib/spell-check-view.coffee, package.json, spec/spell-check-spec.coffee
Closes #157
Closes #228
Fixes #117
Currently, spell-checking is enabled and disabled via a setting called `spell-check.grammars` whose value is a list of top-level grammar names for which to perform spell checking. However, people often want to disable spell-checking for particular syntactic construct within a language for which spell-checking is otherwise enabled (for example, to prevent certain keywords in a LaTeX document from being marked as misspelled).
This PR adds a new setting called `spell-check.excludedScopes`. The value of this setting is an array of scope selectors (e.g. `['.support.function.tex', '.link']`). Currently, nested selectors are not supported: you can only use combinations of one or more class names.
I think that in the future, we could replace the existing …
=> Add excludedScopes setting

README.md
Add note about SPELLCHECKER_PREFER_HUNSPELL to README.md
See [spellchecker/src/spellchecker_win.cc:270-274](https://github.com/atom/node-spellchecker/blob/aed067edabd34d88b699e9cc3a6d4244c832782e/src/spellchecker_win.cc#L270-L274). That's of course assuming this works since I didn't really verify that it does.
=> Add note about SPELLCHECKER_PREFER_HUNSPELL to README.md

package.json, spec/known-unicode-spec-checker.coffee, spec/spec-checker.coffee, spec/spell-check-spec.coffee
I've added a positive and negative test as the first commit to prove the defect and then a second commit for the correction.
The "known words" part of `spell-check` could not handle non-Latin words due to the use of the `\w` in the regular expressions. This is a known problem because of Javascript's poor Unicode support. To fix it, `spelling-manager` was updated to use Unicode ranges for character identification instead of `\w`. In specific, `\p{L}\p{M}\p{N}\p{Pc}`. It does not use `[\p{InEnclosedAlphanumerics}&&\p{So}]` as suggested in #219 because of poor support of logical character ranges.
Previous iterations of `spelling-manager` went with the `\w` because of common usage. Since this was a centralized function used by `spell-check` known words and `spell-check-project`, it seemed …
=> Unicode known words

package.json, script/postinstall.js
In an attempt to resolve the problem described in https://github.com/atom/spell-check/issues/67#issuecomment-377808833, this pull request adds a postinstall hook to delete the webworker-threads module as described in https://github.com/atom/spell-check/issues/67#issuecomment-380298141.
This is admittedly a hack, and I'm not _certain_ that it will resolve the issue, but we'll give it a shot.
If this does resolve the issue, we can consider it a temporary workaround, and we can remove this workaround when the spelling-manager module no longer depends on the natural module (https://github.com/atom/spell-check/issues/67#issuecomment-380471302), or when the natural module makes the webworker-threads module a peer dependency (https://github.com/NaturalNode/natural/issues/368) instead of an …
=> Add postinstall hook to remove the webworker-threads module

lib/system-checker.coffee, package.json
* Added an enum setting to disable error reporting.
* Default to reporting both to the console and popup.
* Refactored to be able to show the list of all paths used to search for
dictionaries.
To make it easier to identify quickly there are problems loading a system dictionary, some sort of notification would be helpful. Having a list of all the paths searched would also make it easier in the process of implementing/using relative paths for dictionaries. This patch is to have a popup show on loading errors to let the user know there is a problem and some diagnostics information.
I considered only reporting the paths to the console but it felt like it was an easily hidden spot that made it difficult to identify where the problem was happening.
The user will be able to identify loading or …
=> Added the ability to show loading errors as a transient popup.

lib/main.coffee, lib/spell-check-view.coffee, spec/spell-check-spec.js
Fixes #238
There were two bugs in the the logic for excluding scopes:
1. Due to the wrong `Config` method being called, the excluded scopes were only used when the `excludedScopes` setting *changed*, not during initialization of the packages.
2. The misspellings needed to be updated after the buffer finished tokenizing, because when initially spell-checking a file, the scopes might not be present.
=> Ensure excluded scopes are respected

PLUGINS.md, lib/main.coffee, lib/spell-check-manager.coffee
When I originally wrote the plugin infrastructure, I had to use `require.resolve` to pass in the paths to the checker for the secondary processes. At the time, I was only using Coffee and ES5, so I just created a new version of the object and returned that.
When using later versions of Typescript and ES6, this is more difficult to do because of how ES6 modules work.
When we load the checker via `require`, check to see if `require.default` exists. If it does, then treat it as a class that needs to be `new checker.default()`.
Getting Typescript to generate a top-level instantiated object is difficult but not impossible. I thought it was better to allow working with the language and handling the two cases in the `spell-check` code instead of jumping through hoops with the plugins.
Easier …
=> Allow for ES6 checkers that are exported as a default class.

lib/system-checker.coffee, package.json
* User can use pseudo-drives to create relative paths:
* Implement [atom-pathspec](https://www.npmjs.com/package/atom-pathspec)
* Issue #203 would use `application:../dictionaries` for searching.
* Addresses some issues referenced in #204.
* See above link for how to use home-, download-, and configuration-relative paths.
* Added no new tests because couldn't find a way of referencing relative paths in a test.
* All new code requires tests to ensure against regressions
Not sure how to write tests that use a relative path since that is outside of the test.
Issue #203 is asking for the ability to have a relative path for dictionary search paths for portable installations. This introduces the concept of pseudo-drives for path specifications to allow Electron to use those as a root and enable …
=> Added the ability to have a relative path for dictionary lookup.

appveyor.yml
spell-check is no longer building correctly against Atom Beta due to some conflict between Electron 2.0 and the build tools on AppVeyor.
=> Fix AppVeyor builds against Atom beta with Electron 2.0.1

lib/main.coffee
We've received internal reports that `spell-check` still doesn't seem to have great performance characteristics for very large files (not sure if there are plans to fix this :P)
Unfortunately, the check to disable spell-check on large files was using `editor.largeFileMode`, which is no longer a supported API (It's now part of `TextMateLanguageMode`, which we can't really count on).
https://github.com/atom/atom/search?q=largeFileMode&unscoped_q=largeFileMode
Instead, we'll just get the buffer's length and compare it to our own `LARGE_FILE_SIZE` (set to 2MB, the same as the one in `TextMateLanguageMode`.)
=> Fix large file check

lib/main.coffee
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
If the `TextEditor` was ignored by the observe callback on all `TextEditor`s there was a good reason for that (currently large files). Respect that and handle when the `TextEditor` isn't currently in the list of `spellCheckViews`.
There is probably a more "CoffeeScripty" way of doing this check, but as this code should be converted to JavaScript anyway this isn't really relevant.
No error is thrown to the user.
No feedback to the user that their command did nothing if they _wanted_ to spell check a `TextEditor` that was ignored.
Fixes #210.
=> Ignore unregistered TextEditors

package.json
`node-spellchecker@3.5.3` contains [a fix](https://github.com/atom/node-spellchecker/pull/108) for Node v12 builds (which will be relevant when upgrading to Electron v5).
=> ⬆️ node-spellchecker@3.5.3

README.md, lib/checker-env.coffee, lib/known-words-checker.coffee, lib/locale-checker.coffee, lib/main.coffee, lib/spell-check-manager.coffee, lib/system-checker.coffee, package.json, spec/spell-check-spec.js
While investigating https://github.com/atom/atom/issues/15912, the problem seemed to be based on calling the macOS built-in checking library with different locales. With multiple languages, that would call it with first one and then the second. Eventually, there would be an error thrown that caused the system to crash.
Then, while working on that item, we identified a problem where certain Windows 10 installations (in my case, an enterprise-distributed one) don't always provide spell-checking for non-English dictionaries and therefore couldn't use the built-in language for non-English (or whatever) languages.
In both of these cases, we need to be able to use system checker in a generic manner (without specifying language) or force the use of Hunspell even without the environment variable. …
=> Split checkers to explictly handle macOS/Windows system checkers verses locale-based checking

DEVELOP.md, README.md, lib/locale-checker.coffee, lib/main.coffee, lib/spell-check-manager.coffee, lib/system-checker.coffee, package.json, spec/locale-checker-spec.js
The recent changes to split system and locale checkers have caused some trouble with Windows Spell Checking and spurious warnings on Mac. This is to resolve them as described in https://github.com/atom/spell-check/issues/328. In specific:
- Windows with the default settings of "Use System" and "Use Locale" does not work with the default language.
- Mac with the default settings shows a warning though system checking is working correctly.
Many of these issues also show up when the default locale is *not* `en-US`.
The main difficulty is coordinating the various rules that have to be applied:
- Mac *cannot* define locales or paths for system checking to avoid process crashes.
- Windows *must* define locales but *cannot* provide a path to use Spelling API.
- Linux must use locales. System …
=> Fix issues with Windows and Mac checking, reduce noise

lib/locale-checker.js, lib/main.js, lib/spell-check-manager.js, lib/system-checker.js, package.json
- Makes debug loading lazy and hides it behind a setting. This is inline with Atom's snapshot system
- This adds a config which allows to enable or disable debug
- Allows spell-check to be included in the snapshot -> Unblocks https://github.com/atom/atom/pull/21777
- Adding UI for debugging makes it easier for normal users to enable/disable debugging.
- No extra overhead because of debug package. 
- Loading time is decreased from 29ms to 15ms
N/A
Fixes #356
=> Add enableDebug to config

lib/spell-check-task.js
This fixes the errors thrown by `language-todo` and `language-hyperlink`
=> Fixes unable to load package
